/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Assignment6View;

import java.util.List;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

import Assignment6Controller.CustomerDAO;
import Assignment6Model.BankCustomer;



/**
 *
 * @author karunmehta
 */
public class CustomerList extends javax.swing.JFrame {



    
    
    /**
     * Creates new form CustomerList
     */
    public CustomerList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        details = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        custList = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(10, 5));

        details.setText("Show Details");
        details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsActionResult(evt);
            }
        });

        cancel.setText("Cancel");

        jLabel1.setText("Customer List:");

        // Inside the initComponents method
        custList.setModel(new javax.swing.AbstractListModel<BankCustomer>() {
            List<BankCustomer> customers = BankCustomer.getCustomers(); // Adjust based on actual method to fetch customers
            public int getSize() { return customers.size(); }
            public BankCustomer getElementAt(int i) { return customers.get(i); }
        });


        jScrollPane1.setViewportView(custList);

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel5.setText("List of Customers");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(details)
                        .addGap(68, 68, 68)
                        .addComponent(cancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(137, 137, 137))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel5)
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(details)
                    .addComponent(cancel))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // This method is triggered when the "Show Details" button is clicked
    
    private void detailsActionResult(java.awt.event.ActionEvent evt) {
        BankCustomer selectedCustomer = custList.getSelectedValue();
        if (selectedCustomer == null) {
            JOptionPane.showMessageDialog(this, "No customer selected!");
            return; // Early exit if no customer is selected
        }
    
        CustomerDAO dao = new CustomerDAO();
        // Assuming that selectedCustomer might be partially loaded and needs full details
        BankCustomer customerDetails = dao.getCustomerById(selectedCustomer.getCusId());
        
        if (customerDetails == null) {
            JOptionPane.showMessageDialog(this, "Customer details not found.");
            return; // Exit if no full details are found
        }
    
        // At this point, customerDetails should be fully loaded
        CustomerDetail detailWindow = new CustomerDetail(customerOverridden(selectedCustomer, customerDetails));
        detailWindow.setVisible(true);
    }
    
    // Method to override selectedCustomer data with any additional details found in customerDetails
    private BankCustomer customerOverridden(BankCustomer selectedCustomer, BankCustomer customerDetails) {
        selectedCustomer.setFirstName(customerDetails.getFirstName() != null ? customerDetails.getFirstName() : selectedCustomer.getFirstName());
        selectedCustomer.setLastName(customerDetails.getLastName() != null ? customerDetails.getLastName() : selectedCustomer.getLastName());
        selectedCustomer.setEmail(customerDetails.getEmail() != null ? customerDetails.getEmail() : selectedCustomer.getEmail());
        selectedCustomer.setPhone(customerDetails.getPhone() != null ? customerDetails.getPhone() : selectedCustomer.getPhone());
        selectedCustomer.setAddress(customerDetails.getAddress() != null ? customerDetails.getAddress() : selectedCustomer.getAddress()); // Assuming there's a getAddress method
        // Include other details as necessary
        return selectedCustomer;
    }
    

    

    
    
    
    
    public void showCustomerDetail() {
        if (custList.getSelectedValue() != null) {
            BankCustomer selectedCustomer = custList.getSelectedValue();
            CustomerDetail detailFrame = new CustomerDetail(selectedCustomer);  // Updated to use the new constructor
            detailFrame.setVisible(true);

            System.out.println("Customer Details:");
            System.out.println("First Name: " + selectedCustomer.getFirstName());
            System.out.println("Last Name: " + selectedCustomer.getLastName());
            System.out.println("Email: " + selectedCustomer.getEmail());
            System.out.println("Phone: " + selectedCustomer.getPhone());

        } else {
            JOptionPane.showMessageDialog(this, "No customer selected", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    
    
    
    
    
    
    
     

    
    
    

    // Assume BankCustomer has a meaningful toString() override that will display customer details appropriately

    // Add a method to update the JList with customer data
    public void displayCustomers(List<BankCustomer> customers) {
    DefaultListModel<BankCustomer> model = new DefaultListModel<>();
    for (BankCustomer customer : customers) {
        model.addElement(customer);  // Add BankCustomer objects directly
    }
        custList.setModel(model);
    }


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JList<BankCustomer> custList;
    private javax.swing.JButton details;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
